language: scala
scala:
- 2.12.1
- 2.11.8
jdk:
- oraclejdk8
install:
- ". $HOME/.nvm/nvm.sh"
- nvm install stable
- nvm use stable
- npm install
- npm install jsdom source-map-support jsdom-global
env:
  global:
  - secure: QtjGA1az13DSVNzOiQOGpJgaJuF5HM1SXMZZYQv3FfNSL5Ek2pvaT66cFXo2DQucmL6K8yUTOugPMP/d1UJBp/guhmzr8be9XfMRClDNz8ESpWs9gXRrq7BGReIRCnBvfoZOWNTOZhYsgr/6U2srr+2T/Cn6vfsbCRQaeEeEYkg1dzcuSS7jvbYO90WAAAVaXPw3oZ5ypxa7LORla2xJoxQdUQIh1PlWhEARRZ+BXywmcf89pnqGR2ml4wVUlZ91bfpzB9AHntShqod3a4B338qvnwgMW0OWj7oShZq9RCsnrHvmLRkLZ0pqyw8mGzowwUHbrb/qnqAengvCMd2McEOTfab8hT639yPz48z/mZ8CFSf+Vx43G+eLT1l8zlWZY/entV03DB1vkRsV5TPt1Lt5/f+o10muIm1bux8oIRZu49Nl7xpaAJ0UK61A+YWWxTXqn8/67tF+fb2ERVlJlRHNjR3lFmUFVAK7FREq1GjYSsGeKC/LU3JUBmSPmQZLCvvoaK5LZTyjHgGTYy071GXGSX5yTFEhpOXkTMwv8uRkw7bjC7samfAQs8Y4si4lHSlwv+khCdgMMGDxhuFPA0xoDw6NgZuKQR50IPtQgnrd5xc1Cggz/IC3+6BS6zSqXqR/Gi+HBbAbjR/VxAkqSD4IwMNQpYQ0ZiLNV7WxZUA=
  - secure: kys/sedHNmCpDydv3uYUbIQ4DUj/Mfqrmku4AqfD295cw4uJz0aTQZr4dLEc4I97ZammC3CxA027ZaIHL5qGMfotibCQmkwfUMu8ea+ApXvg77RGMzBR2HF6e3ayyLFhwIsEKwqa8Jdg3WdSgdHlFPR8CtiuhwLweYYew8zK/iUPaX+Q7Dvz4cy8brDeMhpxs6+nlXpV6iV1w4xOa2pqO+0CwDLtlMizOb+/V2Vsnv6b/bA8V/cBe/tdeKXgHsw+R94jZWd5IwWVUgu8G/0pH53BC76rEFpHDliZjf49gMCbte0x75lXwounWunLvJ368UP1cJ+g7dqXQuw8CwlHIZOz1yn6vekmUmbw0sgcCDqzcxqkWzMgzxFkslWusLsj04WWO+PmYviQkwSWXObkxhtAl3CSjNDAanDg729X25ACoZ8olDgDYd6KeVBlKeX2q1Vu+q/pgkQq9OrMOaCIJlSU/jHTnlv5HHj6YmCPmivVrihxBhmMvXBgURwaoEXK+F9StWGzBdW6aeYIsAQmTvV71ALPLIBmdFv9Gyh47/J2Zwik2TKG/yqTvr4agbHm4xTn2ZHoJ7Fu1lEkJjFXBE45VKpRWlYGWk4gHg/7JOZS93VdJds51Q1ece8mCEXGhN0jVqAX7Zk0otYCFvFdma7s3hj7Zh/dLI6dQcUgSgM=
script:
- sbt ++$TRAVIS_SCALA_VERSION test:fastOptJS test:fullOptJS
- sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' test
- sbt ++$TRAVIS_SCALA_VERSION 'set parallelExecution in ThisBuild := false' 'set scalaJSStage
  in ThisBuild := FullOptStage' test
deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt publish
  on:
    tags: true
